spring:
  profiles:
    active: development
  datasource:
    url: jdbc:mariadb://mariadb:3306/test
    username: root
    password: secret
  flyway:
    database: mariadb
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true

server:
  error:
    include-message: always
